README.md
backoff/pkg.go
retry/pkg.go

add backoff

---

audittools/doc.go
audittools/trail.go

amqp dependency was introduced in #13. We build and parse the URL directly in the `pkg/config` file in our go project, which is shared between other projects. Adding amqp causes useless dependencies to all other projects, which use our initial `pkg/config`. Since it is just a URL and you convert it back to string I think it'd be wise to revert this back and keep the initial func args order: url, queue.

Remove amqp dependency from audittools/trail.go

---

audittools/rabbitmq.go
go.mod
go.sum

streadway/amqp is not maintained anymore. It was forked by the RabbitMQ core team for continued development.

audittools: switch to official amqp library from RabbitMQ

---

README.md
easypg/easypg.go
easypg/testhelpers.go
sqlext/doc.go
sqlext/interfaces.go
sqlext/utils.go

In this PR:
This new package contains a bunch of helper functions for SQL statements that are independent of Postgres and thus don't really fit into "easypg".
Most of these functions originate from Limes, except for WithPreparedStatement that started in Keppel. All have been copied around quite a bit ever since. The implementations have not been changed from their imported versions, except for type name adjustments and `s/interface{}/any/`.
Where the original names included "SQL", this part has been dropped from the names since the package is already named "sqlext". For example, we have SimplifyWhitespaceInSQL which is now "sqlext.SimplifyWhitespace".
Some new test helper functions are added to aid with reproducible test setup. These, too, originate from Limes and have been copied around …

extend SQL utility libraries

---

gopherpolicy/pkg.go
httpext/server.go
httpext/transport.go
httpext/transport_test.go

The first commit standardizes some common logging choices that we are currently copy-pasting between applications. Merging this will initially cause double-logging, which is not destructive, just a bit weird, and I will take care of removing the respective log lines from the application code once the PR is merged.
The bigger addition is `httpext.WrapTransport()`, which provides a standardized interface for the manipulation of `http.DefaultTransport`. This replaces other pieces of code that I keep copy-pasting. For example, <https://github.com/sapcc/limes/blob/master/pkg/util/http.go#L38-L44> can be rewritten as:
```go
wrap := httpext.WrapTransport(&http.DefaultTransport)
wrap.SetInsecureSkipVerify(osext.GetenvBool("LIMES_INSECURE"))
wrap.Attach(func (rt http.RoundTripper) …
```

add httpext.WrapTransport(), standardize common logging choices

---

README.md
pluggable/pluggable.go
pluggable/pluggable_test.go

In all our big services, we have some sort of interface boundary that separates the core business logic from concrete implementations connecting to specific outside services:
* castellum: AssetManager
* limes: DiscoveryPlugin, QuotaPlugin, CapacityPlugin
* keppel: AuthDriver, StorageDriver, FederationDriver, InboundCacheDriver, RateLimitDriver
* tenso: ValidationHandler, TranslationHandler, DeliveryHandler
Each of these plugin interfaces uses the same ca. 20 LOC for registering and instantiating plugin types. If it were only for the code duplication, I would not even be doing this PR. But the sheer amount of tiny differences between these plugin interfaces is getting on my nerves more and more. This PR adds a type-safe base implementation of a plugin registry to go-bits that I want to …

add package "pluggable"

---

jobloop/cron.go
jobloop/producer_consumer.go
jobloop/tx_guarded.go

This makes runtime errors as the following easier to find and fix:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xabc514]
goroutine 152 [running]:
github.com/sapcc/go-bits/jobloop.(*TxGuardedJob[...]).discoverTask(0xe28c80, 0xc1ed80)
/src/vendor/github.com/sapcc/go-bits/jobloop/tx_guarded.go:102 +0x74
github.com/sapcc/go-bits/jobloop.(*ProducerConsumerJob[...]).produceOne(0x10)
/src/vendor/github.com/sapcc/go-bits/jobloop/producer_consumer.go:103 +0xe8
github.com/sapcc/go-bits/jobloop.producerConsumerJobImpl[...].ProcessOne(0xe2c320?)
/src/vendor/github.com/sapcc/go-bits/jobloop/producer_consumer.go:126 +0x29
github.com/sapcc/go-bits/jobloop.producerConsumerJobImpl[...].runSingleThreaded(0xe2c320?, …
```

jobloop: panic if required functions are not provided

---

httpapi/pprofapi/pprofapi.go

httpapi: add pprofapi, wrapping net/http/pprof with an authorization hook

---

promquery/bulkquerycache.go
promquery/bulkquerycache_example_test.go

This implementation originates in Limes (imported from there at `internal/util/promcache.go`), but I want to reuse it in Castellum where the idea of bulk requesting and caching Prometheus metrics originates.
This implementation differs slightly from the one in Limes:
- The `Prometheus` prefix was removed from the type names to fit the package name.
- The `refreshRate` field was renamed to `refreshInterval` ("rate" would be the inverse of an interval).
- The constructor method takes a Client instance instead of its Config to avoid double initialization work in the general case.
- A full-featured documentation example was added to better demonstrate how all the pieces fit together.
~~**Note:** Because of the year-end change freeze, please do not merge this yet. Once approved, I will merge …

promquery: add BulkQueryCache

---

respondwith/pkg.go

Based on our investigation of doop-api.

respondwith.JSON: avoid extra buffer allocations

---

audittools/rabbitmq.go

We use persistence with our rabbitmq clusters, this must be set as persistent when publishing.

audittools: add persistence to publishing

---

promquery/bulkquerycache.go

This PR aims to prevent the processing of empty prometheus query results in applications that use this library. A scenario was sighted in Limes where the source applications did not provide data to prometheus for a certain time period.

Add handling to empty prometheus queries

---

promquery/config.go

I eventually want to get rid of YAML for config parsing because of the sorry state of YAML libraries in Go.

promquery: support deserialization of type Config from JSON

---

liquidapi/liquidapi.go

I initially thought to use GET /v1/info for Kubernetes probes, but that does not work because the kubelet does not have a Keystone token.

liquidapi: add GET /healthcheck

---

assert/assert.go
errext/errext_test.go
osext/env_test.go

If both sides are of different types, then `reflect.DeepEqual()` will always fail. This looks like something that we ought to detect on the type level.

assert: ensure that both sides of DeepEqual() are of the same type

---

regexpext/regexpext.go
regexpext/regexpext_test.go

This reduces pressure on the LRU cache holding compiled regex instances. In Limes, we currently have >100 BoundedRegexp instances in our config file, but the cache only has 64 entries, so it is constantly being thrashed.

regexpext: avoid compiling to regexp when the pattern is a literal

---

regexpext/configset.go
regexpext/configset_test.go

This type is a distillation of what already exists (in a messier way) in Limes' ResourceBehavior type. I plan to rebase ResourceBehavior on top of it, but the notion could also be useful elsewhere.
It does not copy the `Merge` functionality from type ResourceBehavior because that's the part that I want to get rid of. The Merge thing is only necessary because different behaviors can set very disparate fields, so we would have to merge one that controls capacity overcommit with one that controls commitment configuration and so on. By having this type generic over the actual encapsulated value type, I intend to have multiple ConfigSets for the different fields of type ResourceBehavior, thus removing the need for merging altogether.

regexpext: add type ConfigSet

---

gopherpolicy/pkg.go
gopherpolicy/serialize.go
gopherpolicy/serialize_test.go

As the comments suggest, I intend to use this in the JWT tokens issued by Keppel, to shave off several 100 bytes for each token.

gopherpolicy: add a compact serialization for Context objects

---

liquidapi/client.go
liquidapi/liquidapi.go

This implementation comes from Limes (`internal/plugins/client_liquid.go`) and moves here in order to be usable from limesctl.

liquidapi: add type Client

---

README.md
gophercloudext/auth.go

This is a significantly trimmed down version of https://pkg.go.dev/github.com/gophercloud/utils/openstack/clientconfig#AuthenticatedClient, mostly intended to remove the dependency on a YAML parser that gophercloud/utils's support for clouds.yaml pulls in. This instead contains just the feature set that we need for server-side applications like Limes or doop-analyzer. User applications like limesctl should continue using gophercloud/utils for maximum compatibility with whatever weird config the users are running.

add package gophercloudext with func NewProviderClient

---

gopherpolicy/pkg.go
liquidapi/liquidapi.go

Callers can still support policy.yaml files, but they have to explicitly provide a YAML parser function of their choice.
The change in package gopherpolicy is explicitly designed to be loud and obvious when Renovate tries to update, because the function signature changes. Unfortunately, I did not see a good way to make the change in package liquidapi similarly loud and obvious. But since this currently only affects Limes (which is under my control) and liquid-ceph (which we have a direct line of communication to), this ought to be manageable.

gopherpolicy: remove explicit YAML dependency

---

easypg/snapshot.go
gophercloudext/auth.go

Castellum needs a special affordance here because it wants to be able to use its cloud_admin credentials to scope into customer projects for some specific operations. For reference:
https://github.com/sapcc/castellum/blob/5cdaf93ae7dc65ac6e2cb426cd0875aac15e13d1/internal/core/openstack.go#L138-L152

gophercloudext: add ClientOpts.CustomizeAuthOptions

---

liquidapi/liquidapi.go

In order to investigate the high memory usage in liquid-ironic.

liquidapi: enable profiling

---

audittools/event.go
audittools/event_test.go
gopherpolicy/token.go

I was in the process of reworking the dataflow and forgot to match the change on the gopherpolicy side with the audittools side.
To remedy this, an assertion has been added to check that gopherpolicy.Token satisfies the audittools.UserInfo interface.

audittools: fix gopherpolicy integration

---

easypg/easypg.go
easypg/testhelpers.go
easypg/testsetup.go
easypg/url.go

The new test server is completely separate from the one managed by the script (it uses a different data directory and also a different port number), so it can be run in parallel with the old script until all usage has been ported over. Then we can remove the shell script from go-makefile-maker.
I have tested this by porting Castellum to this new version of the library. This can be inspected in <https://github.com/sapcc/castellum/commit/fda939206a237cf9cd2a74fe386f8e18c7a1fa57>.

easypg: replace testing/with-postgres-db.sh with a Go API

---

easypg/testsetup.go

This is something I noticed during local test execution. If the application crashes or the test execution gets exited prematurely, the previous DB connection still lingers around which forces an execution error.

easypg: stop database connection if not existed properly

---

easypg/snapshot.go
easypg/testhelpers.go
easypg/testsetup.go

Ginkgo test suites do not have a `*testing.T`, so we need to use an interface instead.
Additional trickery is needed to deal with how `t.Name()` works under Ginkgo.

easypg: compatibility with onsi/ginkgo

---

README.md
gophercloudext/auth.go
gophercloudext/utils.go
liquidapi/algorithms.go
liquidapi/algorithms_test.go
liquidapi/doc.go
liquidapi/liquidapi.go
liquidapi/utils.go

To make these utility functions available to external LIQUID implementors, such as liquid-ceph.
- `limes/internal/util/algorithms.go` -> `liquidapi/algorithms.go` without any changes
- `limes/internal/util/algorithms_test.go` -> `liquidapi/algorithms_test.go` with one small change (type `db.ProjectServiceID` is replaced by a local type)
- `limes/internal/liquids/utils.go` -> `liquidapi/utils.go` and `gophercloudext/utils.go` except for func PointerTo (which I hope to eliminate in Go 1.24)

liquid: import various algorithms and utils from package limes

---

audittools/auditor.go

In Ginkgo/Gomega, ExpectEvents() does not work because:
- It requires *testing.T, which is inaccessible in Ginkgo. This could be made to work by using a reduced interface (like we did for easypg in #200), but...
- Its error reporting style is incompatible with the fail-on-first-error paradigm of Ginkgo, as also explained in #201.

audittools: add func RecordedEvents for Ginkgo/Gomega compatibility

---

README.md
assert/http.go
httptest/handler.go
httptest/handler_test.go

This is intended as a replacement for type assert.HTTPRequest, which does not play well with Ginkgo/Gomega. The big problem is that it wants to log several lines with t.Errorf() and t.Logf(). But in Ginkgo, Errorf() is aliased to Fatalf(), so we will be missing important log lines after the first error.

add new package httptest

---

liquidapi/algorithms.go

This case is currently crashing in QA because the slice access in the loop below is bounds-checked, but I want to have it crash with a message that generates a useful testcase.

DistributeFairly: generate a testcase when crashing because of overflow

---

liquidapi/algorithms.go
liquidapi/algorithms_test.go

When given very large numbers, `sumOfRequests` would overflow when calculated as a uint64, and therefore `fair` was also computed incorrectly.

liquidapi: fix overflow in DistributeFairly

---

go.mod
go.sum
vault/client.go

In case no VAULT_TOKEN is provided from the environment, this adds the
vault token helper which will read the vault token from:
a) ~/.vault-token in case no token helper is configured
b) the configured token helper configured in ~/.vault (see [1])
[1] https://developer.hashicorp.com/vault/docs/commands/token-helper

vault: add token helper

---

go.mod
go.sum
regexpext/configset.go
regexpext/configset_test.go

This is the way it should have been from the beginning, but the Option[] type was not viable yet when I added ConfigSet in 2024.
But since I never got around to actually using ConfigSet anywhere (and GitHub code search on org:sapcc also does not find any existing usage), I feel confident breaking compatibility here at the last possible moment.

regexpext: change ConfigSet API to use Option[] instead of default values

---

easypg/snapshot.go

In Surveyor, we have a table where the primary key and a foreign key constraint both contain the same column (`subpath`). This leads to this value being duplicated in easypg.Tracker snapshots, for example:
```
DELETE FROM ocm_component_commit_refs WHERE cversion_id = 1 AND repo_id = 1 AND commit_id = NULL AND commit_ref = '1111' AND subpath = '' AND subpath = '';
```

easypg: fix duplicate keys in snapshot

---

jobloop/cron.go
jobloop/metadata.go
jobloop/options.go
jobloop/producer_consumer.go

The implementation already had an affordance for adding extra error context in certain situations, but on ProducerConsumerJob, it was implemented incorrectly. The intent was to produce the longer error message at runtime, when writing error messages to the log file, and keep the shorter error message during tests. But because the single-threaded job loop uses the same code path as the test interface ProcessOne(), we ended up using the
short error format there as well.
This includes two small refactorings:
- Because fixing this with the existing pattern would have added an additional bool argument to more functions, which almost always reads badly in callsites, I went with a new field in type jobConfig instead.
- I also moved the fmt.Sprintf part of the error enrichment into a separate …

jobloop: fix missing error context on single-threaded jobs

---

easypg/snapshot.go

When rendering statements like `INSERT INTO foo VALUES ('bar')`, string literals that contain apostrophes need to have those escaped by doubling them.

easypg: fix quoting in snapshots

---

go.mod
go.sum

For some reason, Renovate neglected to open a PR for updates to this library yesterday.

bump majewsky/gg to v1.3.0

---

assert/assert.go
assert/assert_test.go
httptest/handler_test.go
internal/testutil/mockt.go
must/must.go
osext/env_test.go

These unify all the various ad-hoc test helper methods that we created over the years into two interfaces:
- assert.ErrEqual is for checking non-fatal errors during test execution.
- must.SucceedT and must.ReturnT are for catching fatal errors during test setup/teardown. They are testing.T-based variants of the established functions of the same name without T.
As the code comments indicate, I have agonized over these function signatures for a long time. This changeset may not be the optimal solution, but in the end, I feel that having these is better than having ad-hoc helper functions scattered all over all our codebases.

add additional test assertions: assert.ErrEqual, must.SucceedT, must.ReturnT
